---
- name: Basic Setup
  hosts: all
  vars_files:
    - vars.yml
  roles:
    - base

- name: Monitored host
  hosts: all
  vars:
    _node_exporter_binary_install_dir: '/opt/node_exporter'
    _node_exporter_system_group: 'prometheus'
    _node_exporter_system_user: 'prometheus'
  roles:
    - cloudalchemy.node-exporter

- name: DNS Server
  hosts: dns
  vars:
    coredns_config_file: files/coredns/Corefile.j2
  roles:
    - cloudalchemy.coredns