---
- name: Basic Setup
  hosts: all
  vars_files:
    - vars.yml
  roles:
    - base

- name: Monitored host
  hosts: all
  vars:
    _node_exporter_binary_install_dir: '/opt/node_exporter'
    _node_exporter_system_group: 'prometheus'
    _node_exporter_system_user: 'prometheus'
  roles:
    - cloudalchemy.node-exporter

- name: DNS Server
  hosts: dns
  vars:
    coredns_config_file: files/coredns/Corefile.j2
  roles:
    - cloudalchemy.coredns

- name: BigBlueButton
  hosts: bbb
  vars:
    bbb_letsencrypt_enable: yes
    bbb_letsencrypt_email: admin@ulmlernt.de
    bbb_coturn_enable: no
    bbb_turn_enable: no
    bbb_greenlight_enable: no
    bbb_api_demos_enable: no
  roles:
    - nginx
    - n0emis.bigbluebutton
    - bbb-ulmlernt

- name: Easy Join
  hosts: loadbalancer
  vars:
    nodejs_version: "12.x"
  roles:
    - nginx
    - geerlingguy.nodejs
    - bbb-easy-join

- name: Loadbalancer
  hosts: loadbalancer
  vars:
    redis_port: 6379
    redis_bind_interface: 127.0.0.1
    ruby_install_from_source: yes
    ruby_version: 2.6.6
    ruby_download_url: https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.6.tar.gz
    ruby_install_bundler: yes
    # FIXME: postgres only local?
  roles:
    - nginx
    - geerlingguy.redis
    - role: geerlingguy.postgresql
      become: yes
    - geerlingguy.ruby
    - scalelite
