---
- name: Basic Setup
  hosts: all
  tags:
    - always
  vars_files:
    - vars.yml
  roles:
    - base

- name: Monitored host
  hosts: all
  tags:
    - always
  vars:
    _node_exporter_binary_install_dir: '/opt/node_exporter'
    _node_exporter_system_group: 'prometheus'
    _node_exporter_system_user: 'prometheus'
  roles:
    - cloudalchemy.node-exporter

- name: DNS Server
  hosts: dns
  tags:
    - dns
  vars:
    coredns_config_file: files/coredns/Corefile.j2
  roles:
    - cloudalchemy.coredns

- name: BigBlueButton
  hosts: bbb
  tags:
    - bbb
  vars:
    bbb_letsencrypt_enable: yes
    bbb_letsencrypt_email: admin@ulmlernt.de
    bbb_coturn_enable: no
    bbb_turn_enable: no
    bbb_greenlight_enable: no
    bbb_api_demos_enable: no
  roles:
    - nginx
    - n0emis.bigbluebutton
    - bbb-ulmlernt

- name: Easy Join
  hosts: loadbalancer
  vars:
    nodejs_version: "12.x"
  tags:
    - loadbalancer
  roles:
    - nginx
    - geerlingguy.nodejs
    - bbb-easy-join

- name: Loadbalancer
  hosts: loadbalancer
  tags:
    - loadbalancer
  vars:
    redis_port: 6379
    redis_bind_interface: 127.0.0.1
    ruby_install_from_source: yes
    ruby_version: 2.6.6
    ruby_download_url: https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.6.tar.gz
    ruby_install_bundler: yes
    postgresql_hba_entries:
      - {type: local, database: all, user: postgres, auth_method: peer}
      - {type: local, database: all, user: all, auth_method: peer}
      - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: trust}
      - {type: host, database: all, user: all, address: '::1/128', auth_method: trust}
    postgresql_users:
      - name: scalelite
        state: present
    postgresql_databases:
      - name: scalelite
        owner: scalelite
        state: present
  roles:
    - nginx
    - geerlingguy.redis
    - role: geerlingguy.postgresql
      become: yes
    - geerlingguy.ruby
    - scalelite
