---
roles:
  - name: cloudalchemy.node-exporter
    version: 0.19.0
  - name: cloudalchemy.coredns
    version: 0.3.2
## currently using our own fork
#  - name: n0emis.bigbluebutton
  - name: geerlingguy.nodejs
    version: 5.1.1
  - name: geerlingguy.docker
    version: 2.7.0