---
- name: Ensure group "scalelite" exists
  group:
    name: scalelite
    state: present

- name: Ensure user scalelite exists
  user:
    name: scalelite
    shell: /bin/bash
    password: '!'
    update_password: on_create
    groups: scalelite
    state: present

- name: Checkout scalelite repository
  git:
    repo: https://github.com/blindsidenetworks/scalelite.git
    dest: /var/www/scalelite

- name: Ensure scalelite is owner of /var/www/scalelite
  file:
    path: /var/www/scalelite
    recurse: yes
    owner: scalelite
    group: scalelite

- name: Ensure Bundler 2 is installed
  gem:
    name: bundler
    state: latest
    user_install: no

- name: Ensure sqlite is installed
  apt:
    name:
      - sqlite3
      - libsqlite3-dev
    state: present

# bundler: deployment mode by cli argument is deprecated, so we're going to run this:
- name: Ensure bundle in is deployment mode
  command:
    cmd: bundle config set deployment 'true'
    chdir: /var/www/scalelite
    creates: /var/www/scalelite/.bundle/config
  become: yes
  become_user: scalelite

- name: Ensure gems for scalelite are installed
  bundler:
    state: present
    chdir: /var/www/scalelite
  become: yes
  become_user: scalelite

- name: Generate scalelite secret key base
  command: openssl rand -hex 64
  register: scalelite_secret_key_base

- name: Ensure environment file for scalelite
  template:
    src: env.j2
    dest: /var/www/scalelite/.env
  become: yes
  become_user: scalelite

- name: Ensure systemd unit for scalelite api
  template:
    src: scalelite-api.service
    dest: /etc/systemd/system/scalelite-api.service

- name: Ensure systemd unit for scalelite poller
  template:
    src: scalelite-poller.service
    dest: /etc/systemd/system/scalelite-poller.service

- name: Ensure systemd target for scalelite
  template:
    src: scalelite.target
    dest: /etc/systemd/system/scalelite.target

- name: Enable scalelite units
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    enabled: yes
  with_items:
    - scalelite-api
    - scalelite-poller

- name: Ensure scalelite is started
  systemd:
    name: scalelite
    state: started

# FIXME: nginx
