---
- name: Ensure nginx site for letsencrypt requests
  template:
    src: http.conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_domain_name}}.alias.http.conf"

- name: Ensure generic nginx config is applied
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ nginx_domain_name}}.alias.http.conf"
    dest: "/etc/nginx/sites-enabled/{{ nginx_domain_name}}.alias.http.conf"
  notify: reload nginx
