---
- name: Ensure git and docker-compose is available
  apt:
    name:
    - git
    - docker-compose
    - docker
    state: present

- name: Create user
  user:
    name: greenlight
    shell: /bin/bash
    password: '!'
    update_password: on_create
    groups: nogroup
    state: present

- name: Ensure Greenlight is in Docker group
  user:
    name: greenlight
    groups: docker
    append: yes
    state: present

- name: Checkout greenlight
  git:
    repo: https://github.com/stadtulm/greenlight.git
    dest: /var/build/greenlight
    version: 567690c5559fb418e7cb640d802f33dc308d88cc

- name: Ensure greenlight is owner of /var/build/greenlight
  file:
    path: /var/build/greenlight
    recurse: yes
    owner: greenlight
    group: greenlight

 
- name: Build greenlight Image for Ulmlernt
  shell:
    cmd: ./scripts/image_build.sh ulmlerntgreenlight release-v2
    chdir: /var/build/greenlight
  become: yes
  become_user: greenlight
    
# TODO
# 
# add custom index.html file in /var/www/greenlight
# todo build docker ulmlernt greenlight
#
