---
- name: Ensure git and docker-compose is available
  apt:
    name:
    - git
    - docker-compose
    - docker
    state: present

- name: Create user and ensure user is in docker group
  user:
    name: greenlight
    shell: /bin/bash
    password: '!'
    update_password: on_create
    groups: docker
    state: present

- name: Checkout greenlight
  git:
    repo: https://github.com/stadtulm/greenlight.git
    dest: /var/build/greenlight
    force: yes
    version: ulmlernt
    # version: 567690c5559fb418e7cb640d802f33dc308d88cc

- name: Ensure greenlight is owner of /var/build/greenlight
  file:
    path: /var/build/greenlight
    recurse: yes
    owner: greenlight
    group: greenlight

 
- name: Build greenlight Image for Ulmlernt
  shell:
    cmd: ./scripts/image_build.sh ulmlerntgreenlight release-v2
    chdir: /var/build/greenlight
  become: yes
  become_user: greenlight

# Dont check permissions because ./db must be 999:root
#  - name: Ensure greenlight is owner of /srv/greenlight
#  file:
#    path: /srv/greenlight
#    recurse: yes
#    owner: greenlight
#    group: greenlight

# Backup cleanup:  currently on fsn03: /etc/crontab calls greenlight-backup.sh which pg_dumpall postgrescontainer to lb.ulmlernt.org:/var/backups/greenlight

- name: Ensure Backup Skript for Postgres is present
  template:
    src: greenlight-backup.sh
    dest: /srv/greenlight/greenlight-backup.sh
    owner: srf
    mode: u=rwx,g=r,o=r

# creates entry in personal crontab for user srf
# sudo -u srf crontab -e for edit
- name: Ensure Backupskript runs in cron
  cron:
    name: "Backup Postgres container to remote dest"
    minute: "0"
    hour: "8-22"
    job: "/srv/greenlight/greenlight-backup.sh"
    user: srf

- name: Ensure greenlight nginx conf is present
  template:
    src: greenlight.nginx
    dest: /etc/nginx/a13.d/greenlight.conf
  notify: reload nginx

- name: Ensure docker-compose.yml for greenlight
  template:
    src: docker-compose.j2
    dest: /srv/greenlight/docker-compose.yml

- name: Ensure .env for greenlight
  template:
    src: env.j2
    dest: /srv/greenlight/.env
    owner: greenlight

