---
- name: Register certbot certificate file
  stat:
    path: "/etc/letsencrypt/live/{{ nginx_domain_name }}/fullchain.pem"
  register: certbot_certificate_file_path

- name: Ensure availability of local nginx config
  template:
    src: gl.conf.j2
    dest: /etc/nginx/sites-available/gl.conf

- name: Ensure existence of maintenance folder
  file:
    path: /var/www/html/maintenance
    state: directory

- name: Copy maintenance files
  copy:
    src: "{{item}}"
    dest: "/var/www/html/maintenance/{{item}}"
  with_items:
    - index.html
    - hackhack.gif

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Ensure local nginx config applies
  file:
    state: link
    src: /etc/nginx/sites-available/gl.conf
    dest: /etc/nginx/sites-enabled/gl.conf
  when: certbot_certificate_file_path.stat.exists
  notify: reload nginx
