---
- name: Remove default nginx config
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Ensure folder for letsencrypt exists
  file:
    name: /var/www/letsencrypt
    state: directory
